### ISSUE TITLE
 第9章 発展的なログイン機構

### ISSUE THREAD

**Issue by BitBearDev** [BitBearDev/learn-ruby-on-rails#9]
# TODOs

- [x] 9.1 Remember me 機能
- [x] 9.2 ［Remember me］チェックボックス
- [x] 9.3［Remember me］のテスト
- [x] 9.4 最後に
